// Code generated by muxt generate --use-receiver-type=Service --use-receiver-type-package=github.com/typelate/sortable-example/internal/domain --output-routes-func=Routes. DO NOT EDIT.
// muxt version: v0.18.1

package hypertext

import (
	"bytes"
	"cmp"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"path"
	"strconv"

	"github.com/typelate/sortable-example/internal/database"
)

type RoutesReceiver interface {
	Lists(ctx context.Context) []database.List
	GetList(ctx context.Context, id int32) ListData
	UpdateList(ctx context.Context, listID int32, form UpdateListForm) ListData
}

func Routes(mux *http.ServeMux, receiver RoutesReceiver) TemplateRoutePaths {
	pathsPrefix := ""
	mux.HandleFunc("GET /", func(response http.ResponseWriter, request *http.Request) {
		var td = TemplateData[RoutesReceiver, []database.List]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		ctx := request.Context()
		if len(td.errList) == 0 {
			td.result = receiver.Lists(ctx)
			td.okay = true
		}
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "GET / Lists(ctx)", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, http.StatusOK)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("GET /list/{id}", func(response http.ResponseWriter, request *http.Request) {
		var td = TemplateData[RoutesReceiver, ListData]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		ctx := request.Context()
		idParsed, err := strconv.ParseInt(request.PathValue("id"), 10, 32)
		if err != nil {
			td.errList = append(td.errList, err)
			td.errStatusCode = http.StatusBadRequest
		}
		id := int32(idParsed)
		if len(td.errList) == 0 {
			td.result = receiver.GetList(ctx, id)
			td.okay = true
		}
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "GET /list/{id} GetList(ctx, id)", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, http.StatusOK)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("POST /list/{id}", func(response http.ResponseWriter, request *http.Request) {
		var td = TemplateData[RoutesReceiver, ListData]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		ctx := request.Context()
		idParsed, err := strconv.ParseInt(request.PathValue("id"), 10, 32)
		if err != nil {
			td.errList = append(td.errList, err)
			td.errStatusCode = http.StatusBadRequest
		}
		id := int32(idParsed)
		request.ParseForm()
		var form UpdateListForm
		for _, val := range request.Form["task-id"] {
			value, err := strconv.ParseInt(val, 10, 32)
			if err != nil {
				td.errList = append(td.errList, err)
				td.errStatusCode = http.StatusBadRequest
			}
			form.TaskIDs = append(form.TaskIDs, int32(value))
		}
		if len(td.errList) == 0 {
			td.result = receiver.UpdateList(ctx, id, form)
			td.okay = true
		}
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "POST /list/{id} UpdateList(ctx, id, form)", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, http.StatusOK)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	return TemplateRoutePaths{pathsPrefix: pathsPrefix}
}

type TemplateData[R any, T any] struct {
	receiver      R
	response      http.ResponseWriter
	request       *http.Request
	result        T
	statusCode    int
	errStatusCode int
	okay          bool
	errList       []error
	redirectURL   string
	pathsPrefix   string
}

func (data *TemplateData[R, T]) MuxtVersion() string {
	const muxtVersion = "v0.18.1"
	return muxtVersion
}

func (data *TemplateData[R, T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{pathsPrefix: data.pathsPrefix}
}

func (data *TemplateData[R, T]) Result() T {
	return data.result
}

func (data *TemplateData[R, T]) Request() *http.Request {
	return data.request
}

func (data *TemplateData[R, T]) StatusCode(statusCode int) *TemplateData[R, T] {
	data.statusCode = statusCode
	return data
}

func (data *TemplateData[R, T]) Header(key, value string) *TemplateData[R, T] {
	data.response.Header().Set(key, value)
	return data
}

func (data *TemplateData[R, T]) Ok() bool {
	return data.okay
}

func (data *TemplateData[R, T]) Err() error {
	return errors.Join(data.errList...)
}

func (data *TemplateData[R, T]) Receiver() R {
	return data.receiver
}

func (data *TemplateData[R, T]) Redirect(url string, code int) (*TemplateData[R, T], error) {
	if code < 300 || code >= 400 {
		return data, fmt.Errorf("invalid status code %d for redirect", code)
	}
	data.redirectURL = url
	return data.StatusCode(code), nil
}

type TemplateRoutePaths struct {
	pathsPrefix string
}

func (routePaths TemplateRoutePaths) Lists() string {
	return "/"
}

func (routePaths TemplateRoutePaths) GetList(id int32) string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "list", strconv.FormatInt(int64(id), 10))
}

func (routePaths TemplateRoutePaths) UpdateList(id int32) string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "list", strconv.FormatInt(int64(id), 10))
}
