// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type List struct {
	ID   int32
	Name string
}

type Plan struct {
	ID           int32
	Instructions string
}

type Task struct {
	ID       int32
	ListID   int32
	PlanID   int32
	Priority int32
}
