// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	// interface: ReadOnlyQuerier TaskPriorityUpdater
	ListByID(ctx context.Context, id int32) (List, error)
	// interface: ReadOnlyQuerier
	Lists(ctx context.Context) ([]List, error)
	// interface: TaskPriorityUpdater
	SetTaskPriority(ctx context.Context, arg SetTaskPriorityParams) error
	// interface: ReadOnlyQuerier
	TasksByListID(ctx context.Context, id int32) ([]TasksByListIDRow, error)
}

var _ Querier = (*Queries)(nil)

type ReadOnlyQuerier interface {
	ListByID(ctx context.Context, id int32) (List, error)
	Lists(ctx context.Context) ([]List, error)
	TasksByListID(ctx context.Context, id int32) ([]TasksByListIDRow, error)
}

type TaskPriorityUpdater interface {
	ListByID(ctx context.Context, id int32) (List, error)
	SetTaskPriority(ctx context.Context, arg SetTaskPriorityParams) error
}
